{ config, lib, pkgs, ... }:

let
  cfg = config.services.cont-ai-nerd;

  scripts = pkgs.callPackage ./scripts.nix {};

  # Compute the common parent directory of all project paths.
  # This is used to strip the prefix and mount under /workspace.
  # Example: ["/home/alice/Projects" "/home/alice/work"] -> "/home/alice"
  findCommonParent = paths:
    let
      # Split each path into components
      splitPath = p: lib.filter (s: s != "") (lib.splitString "/" p);
      allComponents = map splitPath paths;
      
      # Find common prefix of all component lists
      minLen = lib.foldl' (acc: cs: lib.min acc (lib.length cs)) 
                          (lib.length (lib.head allComponents)) 
                          allComponents;
      
      # Check if all paths have the same component at index i
      allSameAt = i: 
        let comp = lib.elemAt (lib.head allComponents) i;
        in lib.all (cs: lib.elemAt cs i == comp) allComponents;
      
      # Find how many components are common
      commonCount = lib.foldl' 
        (acc: i: if acc == i && allSameAt i then i + 1 else acc) 
        0 
        (lib.range 0 (minLen - 1));
      
      # Build the common parent path
      commonComponents = lib.take commonCount (lib.head allComponents);
    in 
      if lib.length paths == 0 then "/"
      else if lib.length paths == 1 then lib.head paths
      else "/" + lib.concatStringsSep "/" commonComponents;

  commonParent = findCommonParent cfg.projectPaths;

  # Convert a host path to its container-side equivalent under /workspace
  getContainerPath = hostPath:
    if hostPath == commonParent then
      # Single path case: hostPath equals commonParent, use basename
      # e.g., /home/alice/Projects -> /workspace/Projects
      "/workspace/${builtins.baseNameOf hostPath}"
    else
      let
        suffix = lib.removePrefix commonParent hostPath;
        cleanSuffix = if lib.hasPrefix "/" suffix then suffix else "/" + suffix;
      in "/workspace" + cleanSuffix;

  # Map of host paths to container paths
  containerPaths = lib.listToAttrs (map (p: 
    lib.nameValuePair p (getContainerPath p)
  ) cfg.projectPaths);

  # Generate config.json from module options
  configJson = pkgs.writeText "cont-ai-nerd-config.json" (builtins.toJSON {
    primary_user  = cfg.primaryUser;
    primary_home  = cfg.primaryHome;
    project_paths = cfg.projectPaths;
    path_map      = containerPaths;
    agent_user    = cfg.agent.user;
    host          = cfg.server.host;
    port          = cfg.server.port;
    install_dir   = "${scripts}/lib/cont-ai-nerd";
  });

  # Generate opencode.json policy file using container-side paths
  opencodePolicy = pkgs.writeText "cont-ai-nerd-opencode.json" (builtins.toJSON {
    "$schema" = "https://opencode.ai/config.json";
    permission.external_directory =
      lib.listToAttrs (map (p: lib.nameValuePair "${containerPaths.${p}}/**" "allow") cfg.projectPaths);
  });

  # Render the Quadlet .container file with Nix-substituted values.
  # Volume lines map host paths to /workspace container paths.
  volumeLines = lib.concatMapStringsSep "\n" (p:
    "Volume=${p}:${containerPaths.${p}}:rw"
  ) cfg.projectPaths;

  containerFile = pkgs.writeText "cont-ai-nerd.container" ''
    # Podman Quadlet - cont-ai-nerd (generated by NixOS module)
    [Unit]
    Description=cont-ai-nerd - Sandboxed AI Agent Container
    After=network-online.target

    [Container]
    ContainerName=cont-ai-nerd
    Image=localhost/cont-ai-nerd:latest

    # The entrypoint runs as root to create host-path symlinks,
    # then drops to the agent user via setpriv.

    # ---------- Bind mounts ----------
    # Project directories (read-write, mounted under /workspace)
    ${volumeLines}

    # cont-ai-nerd generated policy (read-only)
    Volume=${cfg.primaryHome}/.config/cont-ai-nerd/opencode.json:/etc/cont-ai-nerd/opencode.json:ro

    # cont-ai-nerd configuration (for opencode-tui wrapper)
    Volume=${cfg.primaryHome}/.config/cont-ai-nerd/config.json:/etc/cont-ai-nerd/config.json:ro

    # OpenCode global configuration (read-only)
    Volume=${cfg.primaryHome}/.config/opencode:/home/agent/.config/opencode:ro

    # OpenCode auth credentials only (read-only) — the container creates its own log dir
    Volume=${cfg.primaryHome}/.local/share/opencode/auth.json:/home/agent/.local/share/opencode/auth.json:ro

    # ---------- Environment ----------
    Environment=OPENCODE_CONFIG=/etc/cont-ai-nerd/opencode.json

    # ---------- Networking ----------
    Network=host

    # ---------- Resource limits ----------
    PodmanArgs=--memory ${cfg.container.memoryLimit} --pids-limit ${toString cfg.container.pidsLimit}

    # ---------- Entrypoint args ----------
    # Run OpenCode in server mode (headless HTTP server)
    Exec=serve --hostname ${cfg.server.host} --port ${toString cfg.server.port}

    [Service]
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
  '';

  # TUI wrapper script that runs a separate container with rw auth mount.
  # Uses the primary user's GID so the TUI process has the same group
  # permissions as the main container agent.
  tuiScript = pkgs.writeShellScriptBin "cont-ai-nerd-tui" ''
    set -euo pipefail

    CONFIG="${cfg.primaryHome}/.config/cont-ai-nerd/config.json"

    if [[ ! -f "$CONFIG" ]]; then
      echo "Error: Configuration not found at $CONFIG" >&2
      exit 1
    fi

    HOST=$(${pkgs.jq}/bin/jq -r '.host // "127.0.0.1"' "$CONFIG")
    PORT=$(${pkgs.jq}/bin/jq -r '.port // 3000' "$CONFIG")

    AGENT_UID=$(${pkgs.coreutils}/bin/id -u ${cfg.agent.user} 2>/dev/null || echo 1001)
    # Use the primary user's GID — this matches the mapped GID inside the container.
    PRIMARY_GID=$(${pkgs.coreutils}/bin/id -g ${cfg.primaryUser} 2>/dev/null || echo 1000)

    # The container is managed by systemd (rootful podman via Quadlet).
    # A plain `podman ps` run as an unprivileged user only sees the rootless
    # namespace and will never find it.  Checking the systemd unit is reliable.
    if ! systemctl is-active --quiet cont-ai-nerd.service 2>/dev/null; then
      echo "Error: cont-ai-nerd container is not running." >&2
      echo "Start it with: systemctl start cont-ai-nerd" >&2
      exit 1
    fi

    # Ensure OpenCode data directories exist and are owned by the primary user.
    # The activation script creates these, but may not have run if a prior
    # nixos-rebuild failed mid-activation (e.g. image build step aborted).
    # Running as root here (sudo cont-ai-nerd-tui), so we can create and chown.
    for dir in \
      "${cfg.primaryHome}/.config/opencode" \
      "${cfg.primaryHome}/.local/share/opencode" \
      "${cfg.primaryHome}/.local/share/opencode/log"; do
      if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
        chown ${cfg.primaryUser}: "$dir"
        chmod 750 "$dir"
      fi
    done
    AUTH_FILE="${cfg.primaryHome}/.local/share/opencode/auth.json"
    if [[ ! -f "$AUTH_FILE" ]]; then
      echo '{}' > "$AUTH_FILE"
      chown ${cfg.primaryUser}: "$AUTH_FILE"
      chmod 640 "$AUTH_FILE"
    fi

    exec ${pkgs.podman}/bin/podman run --rm -it \
      --name cont-ai-nerd-tui-$$ \
      --user "''${AGENT_UID}:''${PRIMARY_GID}" \
      --network host \
      -v "${cfg.primaryHome}/.local/share/opencode:/home/agent/.local/share/opencode:rw" \
      -v "${cfg.primaryHome}/.config/opencode:/home/agent/.config/opencode:ro" \
      -v "${cfg.primaryHome}/.config/cont-ai-nerd:/etc/cont-ai-nerd:ro" \
      --entrypoint opencode \
      localhost/cont-ai-nerd:latest \
      attach "http://''${HOST}:''${PORT}" "$@"
  '';

in {
  options.services.cont-ai-nerd = {

    enable = lib.mkEnableOption "cont-ai-nerd sandboxed AI coding agent";

    primaryUser = lib.mkOption {
      type        = lib.types.str;
      description = "Login name of the primary (human) user who owns project files.";
      example     = "alice";
    };

    primaryHome = lib.mkOption {
      type        = lib.types.path;
      description = "Home directory of the primary user.";
      default     = "/home/${config.services.cont-ai-nerd.primaryUser}";
      defaultText = lib.literalExpression ''"/home/''${cfg.primaryUser}"'';
      example     = "/home/alice";
    };

    projectPaths = lib.mkOption {
      type        = lib.types.listOf lib.types.path;
      description = ''
        Directories the agent is allowed to access. By setting these paths,
        you opt in to letting the agent read and write files within them
        (subject to standard Unix group permissions).
      '';
      example     = [ "/home/alice/Projects" "/home/alice/work" ];
    };

    agent = {
      user = lib.mkOption {
        type        = lib.types.str;
        default     = "agent";
        description = "Username for the container agent.";
      };
    };

    server = {
      host = lib.mkOption {
        type        = lib.types.str;
        default     = "127.0.0.1";
        description = "Address the OpenCode server listens on.";
      };

      port = lib.mkOption {
        type        = lib.types.port;
        default     = 3000;
        description = "Port the OpenCode server listens on.";
      };
    };

    container = {
      memoryLimit = lib.mkOption {
        type        = lib.types.str;
        default     = "2g";
        description = "Container memory limit (podman --memory flag).";
      };

      pidsLimit = lib.mkOption {
        type        = lib.types.int;
        default     = 100;
        description = "Container PID limit (podman --pids-limit flag).";
      };

      opencodeVersion = lib.mkOption {
        type        = lib.types.str;
        default     = "latest";
        description = "OpenCode version to install in the container image.";
      };
    };
  };

  config = lib.mkIf cfg.enable {

    # -- Podman --
    virtualisation.podman.enable = true;

    # Ensure short image names (e.g., ubuntu:24.04) resolve to docker.io
    virtualisation.containers.registries.search = [ "docker.io" ];

    # -- Users --
    # The agent is a system user on the host (used only for UID mapping).
    # Its host-side group is irrelevant — inside the container, the agent's
    # GID is mapped to the primary user's GID.
    users.users.${cfg.agent.user} = {
      isSystemUser = true;
      group        = cfg.agent.user;
      shell        = pkgs.shadow + "/bin/nologin";
      description  = "cont-ai-nerd container agent";
    };

    # Auto-create the agent's own group on the host (NixOS requirement for system users).
    users.groups.${cfg.agent.user} = {};

    # -- Packages available on the host --
    environment.systemPackages = [
      scripts
      tuiScript
      pkgs.jq
      pkgs.inotify-tools
    ];

    # -- Quadlet container file --
    # Placed at /etc/containers/systemd/cont-ai-nerd.container so the
    # Podman systemd generator picks it up on daemon-reload.
    environment.etc."containers/systemd/cont-ai-nerd.container" = {
      source = containerFile;
      mode   = "0644";
    };

    # -- Activation scripts --
    system.activationScripts = {

      # Ensure config directories and generated files exist.
      cont-ai-nerd-dirs = {
        text = ''
          CONFIG_DIR="${cfg.primaryHome}/.config/cont-ai-nerd"
          mkdir -p "$CONFIG_DIR"
          chown ${cfg.primaryUser}: "$CONFIG_DIR"
          chmod 750 "$CONFIG_DIR"

          # config.json - generated from NixOS module options
          cp --no-preserve=mode ${configJson} "$CONFIG_DIR/config.json"
          chown ${cfg.primaryUser}: "$CONFIG_DIR/config.json"
          chmod 640 "$CONFIG_DIR/config.json"

          # opencode.json - external_directory policy
          cp --no-preserve=mode ${opencodePolicy} "$CONFIG_DIR/opencode.json"
          chown ${cfg.primaryUser}: "$CONFIG_DIR/opencode.json"
          chmod 640 "$CONFIG_DIR/opencode.json"

          # OpenCode config & data directories
          for dir in \
            "${cfg.primaryHome}/.config/opencode" \
            "${cfg.primaryHome}/.local/share/opencode" \
            "${cfg.primaryHome}/.local/share/opencode/log"; do
            mkdir -p "$dir"
            chown ${cfg.primaryUser}: "$dir"
            chmod 750 "$dir"
          done

          # Ensure auth.json exists (required for bind mount, even if empty)
          AUTH_FILE="${cfg.primaryHome}/.local/share/opencode/auth.json"
          if [ ! -f "$AUTH_FILE" ]; then
            echo '{}' > "$AUTH_FILE"
            chown ${cfg.primaryUser}: "$AUTH_FILE"
            chmod 640 "$AUTH_FILE"
          fi
        '';
        deps = [ "users" ];
      };

      # Build / rebuild the container image when needed.
      cont-ai-nerd-image = {
        text = ''
          CONTAINER_DIR="${../container}"
          HASH_FILE="/var/lib/cont-ai-nerd/containerfile.sha256"
          mkdir -p /var/lib/cont-ai-nerd

          CURRENT_HASH=$(${pkgs.coreutils}/bin/sha256sum "$CONTAINER_DIR/Containerfile" | cut -d' ' -f1)
          STORED_HASH=""
          if [ -f "$HASH_FILE" ]; then
            STORED_HASH=$(cat "$HASH_FILE")
          fi

          if [ "$CURRENT_HASH" != "$STORED_HASH" ] || \
             ! ${pkgs.podman}/bin/podman image exists localhost/cont-ai-nerd:latest 2>/dev/null; then

            AGENT_UID=$(${pkgs.coreutils}/bin/id -u ${cfg.agent.user} 2>/dev/null || echo 1001)
            # Use the primary user's GID and group name for the container.
            PRIMARY_GID=$(${pkgs.coreutils}/bin/id -g ${cfg.primaryUser} 2>/dev/null || echo 1000)
            PRIMARY_GROUP=$(${pkgs.coreutils}/bin/id -gn ${cfg.primaryUser} 2>/dev/null || echo users)

            echo "cont-ai-nerd: building container image..."
            ${pkgs.podman}/bin/podman build \
              --build-arg "AGENT_UID=$AGENT_UID" \
              --build-arg "AGENT_GID=$PRIMARY_GID" \
              --build-arg "AGENT_GROUP_NAME=$PRIMARY_GROUP" \
              --build-arg "OPENCODE_VERSION=${cfg.container.opencodeVersion}" \
              -t localhost/cont-ai-nerd:latest \
              -f "$CONTAINER_DIR/Containerfile" \
              "$CONTAINER_DIR"

            echo "$CURRENT_HASH" > "$HASH_FILE"
            echo "cont-ai-nerd: image built successfully."
          else
            echo "cont-ai-nerd: container image up to date."
          fi
        '';
        deps = [ "cont-ai-nerd-dirs" "users" ];
      };

      # Set up project directory permissions.
      # Only ensures directories are group-traversable (g+x) so the agent
      # can navigate via the mapped GID. File permissions are left as-is.
      cont-ai-nerd-permissions = {
        text = ''
          ${lib.concatMapStringsSep "\n" (p: ''
            if [ -d "${p}" ]; then
              ${pkgs.findutils}/bin/find "${p}" -type d ! -perm -g+x -exec chmod g+x {} +
            fi
          '') cfg.projectPaths}
        '';
        deps = [ "cont-ai-nerd-dirs" ];
      };
    };

    # -- Watcher service --
    systemd.services.cont-ai-nerd-watcher = {
      description = "cont-ai-nerd File Ownership Watcher";
      after       = [ "cont-ai-nerd.service" ];
      wants       = [ "cont-ai-nerd.service" ];
      wantedBy    = [ "multi-user.target" ];

      path = [ pkgs.coreutils pkgs.inotify-tools ];

      serviceConfig = {
        Type       = "simple";
        ExecStart  = lib.concatStringsSep " " ([
          "${scripts}/lib/cont-ai-nerd/cont-ai-nerd-watcher.sh"
          cfg.primaryUser
          cfg.agent.user
        ] ++ cfg.projectPaths);
        Restart    = "on-failure";
        RestartSec = 5;
      };
    };

    # -- Commit service (oneshot, triggered by timer) --
    systemd.services.cont-ai-nerd-commit = {
      description = "cont-ai-nerd Container State Commit";

      path = [ pkgs.coreutils pkgs.podman pkgs.gawk pkgs.gnugrep ];

      serviceConfig = {
        Type      = "oneshot";
        ExecStart = "${scripts}/lib/cont-ai-nerd/cont-ai-nerd-commit.sh";
      };
    };

    # -- Commit timer --
    systemd.timers.cont-ai-nerd-commit = {
      description = "Periodic cont-ai-nerd Container Commit";
      wantedBy    = [ "timers.target" ];

      timerConfig = {
        OnCalendar = "daily";
        Persistent = true;
      };
    };
  };
}
