{ config, lib, pkgs, ... }:

let
  cfg = config.services.contain;

  scripts = pkgs.callPackage ./scripts.nix {};

  # Project directories are mounted at their IDENTICAL host paths inside the
  # container (identity mounts). This keeps OpenCode's session `directory`
  # identity canonical: sessions created via the host-side neovim plugin, the
  # attached TUI and the server all record and query the same host-path
  # strings, so directory-scoped session listing survives container
  # recreation and reboots. Podman auto-creates the mountpoint skeleton
  # (root-owned) inside the container; nothing outside the mounted paths is
  # exposed. The former /workspace remapping (+ entrypoint symlink bridge) is
  # gone — it produced divergent directory identities (/workspace/... vs
  # /home/...) that stranded sessions.

  # Generate config.json from module options
  configJson = pkgs.writeText "contain-config.json" (builtins.toJSON {
    primary_user  = cfg.primaryUser;
    primary_home  = cfg.primaryHome;
    project_paths = cfg.projectPaths;
      agent_user    = cfg.agent.user;
      host          = cfg.server.host;
      port          = cfg.server.port;
      internal_port = cfg.server.internalPort;
      on_demand     = cfg.onDemand.enable;
      idle_timeout  = cfg.onDemand.idleTimeout;
      install_dir   = "${scripts}/lib/contain";
      agent_systems = cfg.agentSystems;
  });

  # Generate opencode.json policy file. Host paths are canonical inside the
  # container too (identity mounts), so the allow-list uses them directly.
  opencodePolicy = pkgs.writeText "contain-opencode.json" (builtins.toJSON {
    "$schema" = "https://opencode.ai/config.json";
    permission.external_directory =
      lib.listToAttrs (map (p: lib.nameValuePair "${p}/**" "allow") cfg.projectPaths);
  });

  # Render the Quadlet .container file with Nix-substituted values.
  # Identity mounts: host path == container path.
  volumeLines = lib.concatMapStringsSep "\n" (p:
    "Volume=${p}:${p}:rw"
  ) cfg.projectPaths;

  # The port OpenCode actually binds inside the container. In on-demand mode
  # the public port belongs to contain-proxy.socket and OpenCode listens on
  # the internal port behind the socket-activated proxy.
  listenPort = if cfg.onDemand.enable then cfg.server.internalPort else cfg.server.port;

  containerFile = pkgs.writeText "contain.container" ''
    # Podman Quadlet - contain (generated by NixOS module)
    [Unit]
    Description=contain - Sandboxed AI Agent Container
    After=network-online.target
    ${lib.optionalString cfg.onDemand.enable ''
    # On-demand mode: the container is pulled up by contain-proxy.service
    # (socket-activated) and stopped again once the proxy exits after its
    # idle timeout and nothing else needs the container.
    StopWhenUnneeded=yes
    ''}
    [Container]
    ContainerName=contain
    Image=localhost/contain:latest
    ${lib.optionalString cfg.onDemand.enable ''
    # Delay "started" until the runtime healthcheck passes so the proxy only
    # forwards once OpenCode is actually accepting connections.
    Notify=healthy
    ''}
    # Define health at container creation rather than in image metadata. Podman
    # drops Containerfile HEALTHCHECK from OCI images, while Quadlet's runtime
    # health options work with OCI and are what Notify=healthy observes.
    HealthCmd=curl -sf http://${cfg.server.host}:${toString listenPort}/global/health
    HealthInterval=30s
    HealthTimeout=5s
    HealthRetries=3
    HealthStartPeriod=10s
    # The entrypoint runs as root for volume housekeeping,
    # then drops to the agent user via setpriv.

    # ---------- Bind mounts ----------
    # Project directories (read-write, identity mounts: host path == container path)
    ${volumeLines}

    # contain configuration (for opencode-tui wrapper)
    Volume=${cfg.primaryHome}/.config/contain/config.json:/etc/contain/config.json:ro

    # OpenCode global configuration (read-write; OpenCode persists provider
    # registration and helper files here). The sandbox policy is merged into
    # ~/.config/opencode/opencode.json by contain-opencode-config-seed, so no
    # separate read-only OPENCODE_CONFIG mount is used.
    Volume=${cfg.primaryHome}/.config/opencode:/home/agent/.config/opencode:rw

    # OpenCode data directory (read-write) — database, auth, logs, snapshots, etc.
    Volume=${cfg.primaryHome}/.local/share/opencode:/home/agent/.local/share/opencode:rw

    # OpenCode state directory (read-write) — model preferences, prompt history, etc.
    Volume=${cfg.primaryHome}/.local/state/opencode:/home/agent/.local/state/opencode:rw

    # ---------- Environment ----------
    ${lib.optionalString (cfg.server.passwordEnvFile != null) "EnvironmentFile=${cfg.server.passwordEnvFile}"}

    # ---------- Networking ----------
    Network=host

    # ---------- Resource limits ----------
    PodmanArgs=--memory ${cfg.container.memoryLimit} --pids-limit ${toString cfg.container.pidsLimit}

    # ---------- Entrypoint args ----------
    # Run OpenCode in server mode (headless HTTP server)
    Exec=serve --hostname ${cfg.server.host} --port ${toString listenPort}

    [Service]
    Restart=on-failure
    ${lib.optionalString (!cfg.onDemand.enable) ''
    [Install]
    WantedBy=multi-user.target
    ''}
  '';

  # TUI wrapper script that attaches to the running container.
  # All data (auth, database, model preferences) is persisted via the
  # container's read-write bind mounts — no separate container needed.
  # Runs as the agent user (not root) so files the TUI writes are owned
  # by agent:primary_group and group-writable (umask 002).
  #
  # The TUI's working directory decides the OpenCode session `directory`
  # identity, so it must be one of the (identity-mounted) project paths:
  #   --dir <path>   explicit choice (must be inside a project path)
  #   (omitted)      single project path -> used directly;
  #                  multiple            -> interactive numbered menu.
  tuiScript = pkgs.writeShellScriptBin "contain-tui" ''
    set -euo pipefail

    project_paths=(${lib.concatMapStringsSep " " lib.escapeShellArg cfg.projectPaths})

    usage() {
      echo "Usage: contain-tui [--dir <project-path>] [opencode-tui args...]" >&2
      echo "Project paths:" >&2
      printf '  %s\n' "''${project_paths[@]}" >&2
    }

    workdir=""
    args=()
    while [ $# -gt 0 ]; do
      case "$1" in
        --dir)
          [ $# -ge 2 ] || { usage; exit 1; }
          workdir="$2"
          shift 2
          ;;
        --help|-h)
          usage
          exit 0
          ;;
        *)
          args+=("$1")
          shift
          ;;
      esac
    done

    if [ -n "$workdir" ]; then
      # Accept a project path or any directory beneath one.
      ok=""
      for p in "''${project_paths[@]}"; do
        case "$workdir" in
          "$p"|"$p"/*) ok=1; break ;;
        esac
      done
      if [ -z "$ok" ]; then
        echo "Error: --dir must be a configured project path (or a subdirectory of one)." >&2
        usage
        exit 1
      fi
    elif [ "''${#project_paths[@]}" -eq 1 ]; then
      workdir="''${project_paths[0]}"
    else
      echo "Select project directory:" >&2
      i=1
      for p in "''${project_paths[@]}"; do
        echo "  $i) $p" >&2
        i=$((i + 1))
      done
      printf 'Choice [1-%d]: ' "''${#project_paths[@]}" >&2
      read -r choice
      case "$choice" in
        '''|*[!0-9]*) echo "Invalid choice." >&2; exit 1 ;;
      esac
      if [ "$choice" -lt 1 ] || [ "$choice" -gt "''${#project_paths[@]}" ]; then
        echo "Invalid choice." >&2
        exit 1
      fi
      workdir="''${project_paths[$((choice - 1))]}"
    fi

    sudo_cmd=""
    if [ "$(${pkgs.coreutils}/bin/id -u)" != "0" ]; then
      if [ ! -x /run/wrappers/bin/sudo ]; then
        echo "Error: /run/wrappers/bin/sudo is unavailable; run contain-tui as root or enable sudo." >&2
        exit 1
      fi
      sudo_cmd="/run/wrappers/bin/sudo"
    fi

    ${if cfg.onDemand.enable then ''
    # On-demand mode: warm the container THROUGH the activation socket so
    # the start is attributed to a client connection (correct refcount for
    # StopWhenUnneeded), not to a bare `systemctl start` that could be
    # garbage-collected before the TUI attaches. The health request blocks
    # in the socket backlog until the container reports healthy.
    if ! systemctl is-active --quiet contain.service 2>/dev/null; then
      echo "Starting contain container (on demand)..." >&2
    fi
    # Any completed HTTP response means the server is up (a 401 from a
    # password-protected server still proves liveness), so no -f here.
    if ! ${pkgs.curl}/bin/curl -s -o /dev/null --max-time 180 \
        "http://${cfg.server.host}:${toString cfg.server.port}/global/health"; then
      echo "Error: contain server did not become healthy on ${cfg.server.host}:${toString cfg.server.port}." >&2
      echo "Check: systemctl status contain contain-proxy contain-image" >&2
      exit 1
    fi
    '' else ''
    if ! systemctl is-active --quiet contain.service 2>/dev/null; then
      echo "Starting contain container..." >&2
      $sudo_cmd systemctl start contain.service
    fi
    ''}
    podman_cmd="$sudo_cmd ${pkgs.podman}/bin/podman"

    exec $podman_cmd exec -it --user agent \
      --workdir "$workdir" \
      -e HOME=/home/agent \
      -e XDG_CONFIG_HOME=/home/agent/.config \
      -e XDG_DATA_HOME=/home/agent/.local/share \
      -e XDG_STATE_HOME=/home/agent/.local/state \
      contain sh -c 'umask 002 && exec opencode-tui "$@"' -- "''${args[@]}"
  '';

in {
  options.services.contain = {

    enable = lib.mkEnableOption "contain sandboxed AI coding agent";

    primaryUser = lib.mkOption {
      type        = lib.types.str;
      description = "Login name of the primary (human) user who owns project files.";
      example     = "alice";
    };

    primaryHome = lib.mkOption {
      type        = lib.types.path;
      description = "Home directory of the primary user.";
      default     = "/home/${config.services.contain.primaryUser}";
      defaultText = lib.literalExpression ''"/home/''${cfg.primaryUser}"'';
      example     = "/home/alice";
    };

    projectPaths = lib.mkOption {
      type        = lib.types.listOf lib.types.path;
      description = ''
        Directories the agent is allowed to access. By setting these paths,
        you opt in to letting the agent read and write files within them
        (subject to standard Unix group permissions).
      '';
      example     = [ "/home/alice/Projects" "/home/alice/work" ];
    };

    agentSystems = lib.mkOption {
      type        = lib.types.attrsOf lib.types.attrs;
      default     = {};
      description = "Agent runtime declarations exposed in generated config.json.";
    };

    agent = {
      user = lib.mkOption {
        type        = lib.types.str;
        default     = "agent";
        description = "Username for the container agent.";
      };

      uid = lib.mkOption {
        type        = lib.types.int;
        default     = 473;
        description = ''
          Static UID (also used as the GID of the agent's bookkeeping group)
          for the host-side agent user. Pinned so the UID baked into the
          container image and the ownership of files the agent creates stay
          stable across reboots and image rebuilds — dynamic system UIDs can
          be reallocated. 473 sits well below the dynamic allocation region
          that NixOS fills from 999 downward.
        '';
      };
    };

    server = {
      host = lib.mkOption {
        type        = lib.types.str;
        default     = "127.0.0.1";
        description = "Address the OpenCode server listens on.";
      };

      port = lib.mkOption {
        type        = lib.types.port;
        default     = 3000;
        description = ''
          Public port OpenCode clients connect to. In on-demand mode this is
          the socket-activation port (contain-proxy.socket); otherwise
          OpenCode binds it directly.
        '';
      };

      internalPort = lib.mkOption {
        type        = lib.types.port;
        default     = 3001;
        description = ''
          Port OpenCode binds inside the container when on-demand mode is
          enabled; contain-proxy forwards `port` to it. Unused when
          onDemand.enable is false.
        '';
      };

      passwordEnvFile = lib.mkOption {
        type        = lib.types.nullOr lib.types.str;
        default     = null;
        description = ''
          Optional environment file containing OPENCODE_SERVER_PASSWORD for the
          OpenCode server. The file should be readable by root and not persisted
          unless managed as an encrypted secret.
        '';
      };
    };

    opencode = {
      authSeedFile = lib.mkOption {
        type        = lib.types.nullOr lib.types.str;
        default     = null;
        description = ''
          Optional file merged into the primary user's OpenCode auth store
          (`~/.local/share/opencode/auth.json`) before the container starts.
          Intended for host-managed secrets (e.g. a sops-decrypted path); the
          seed is authoritative for its own keys, while credentials added at
          runtime (e.g. via the TUI /connect flow) are preserved. The store
          is kept agent-writable (0660) because OpenCode >= 1.17 persists
          /connect credentials to auth.json itself.
        '';
      };

      configSeedFile = lib.mkOption {
        type        = lib.types.nullOr lib.types.str;
        default     = null;
        description = ''
          Optional JSON file merged into the primary user's OpenCode config
          (`~/.config/opencode/opencode.json`) before the container starts.
          Layering (later wins): existing runtime config < this seed <
          contAIn's sandbox policy. The file is kept agent-writable (0660):
          OpenCode persists runtime changes (e.g. provider registration from
          /connect) into its config, so a read-only config breaks those
          flows while the seed + policy re-assert declarative keys on every
          service start.
        '';
      };
    };

    onDemand = {
      enable = lib.mkOption {
        type        = lib.types.bool;
        default     = true;
        description = ''
          Start the container on the first client connection (socket
          activation on server.port) and stop it again after idleTimeout
          with no client connections. When disabled, the container starts
          at boot and stays running (legacy always-on behavior).
        '';
      };

      idleTimeout = lib.mkOption {
        type        = lib.types.str;
        default     = "20min";
        description = ''
          systemd time span passed to systemd-socket-proxyd
          --exit-idle-time: how long the proxy waits with zero client
          connections before exiting, which lets the container stop
          (StopWhenUnneeded). Long-lived client connections (the neovim
          plugin's SSE stream, an attached TUI) hold the container up.
        '';
      };
    };

    container = {
      memoryLimit = lib.mkOption {
        type        = lib.types.str;
        default     = "2g";
        description = "Container memory limit (podman --memory flag).";
      };

      pidsLimit = lib.mkOption {
        type        = lib.types.int;
        default     = 100;
        description = "Container PID limit (podman --pids-limit flag).";
      };

      opencodeVersion = lib.mkOption {
        type        = lib.types.str;
        default     = "latest";
        description = "OpenCode version to install in the container image.";
      };
    };
  };

  config = lib.mkIf cfg.enable {

    # -- Podman --
    virtualisation.podman.enable = true;

    # Ensure short image names (e.g., ubuntu:24.04) resolve to docker.io
    virtualisation.containers.registries.search = [ "docker.io" ];

    # -- Users --
    # The agent is a system user on the host (used only for UID mapping).
    # Its host-side group is irrelevant — inside the container, the agent's
    # GID is mapped to the primary user's GID.
    users.users.${cfg.agent.user} = {
      isSystemUser = true;
      uid          = cfg.agent.uid;
      group        = cfg.agent.user;
      shell        = pkgs.shadow + "/bin/nologin";
      description  = "contain container agent";
    };

    # Auto-create the agent's own group on the host (NixOS requirement for system users).
    users.groups.${cfg.agent.user}.gid = cfg.agent.uid;

    # -- Packages available on the host --
    environment.systemPackages = [
      scripts
      tuiScript
      pkgs.jq
      pkgs.inotify-tools
    ];

    # -- Quadlet container file --
    # Placed at /etc/containers/systemd/contain.container so the
    # Podman systemd generator picks it up on daemon-reload.
    environment.etc."containers/systemd/contain.container" = {
      source = containerFile;
      mode   = "0644";
    };

    # -- Activation scripts --
    system.activationScripts = {

      # Ensure config directories and generated files exist.
      contain-dirs = {
        text = ''
          CONFIG_DIR="${cfg.primaryHome}/.config/contain"
          mkdir -p "$CONFIG_DIR"
          chown ${cfg.primaryUser}: "$CONFIG_DIR"
          chmod 750 "$CONFIG_DIR"

          # config.json - generated from NixOS module options
          cp --no-preserve=mode ${configJson} "$CONFIG_DIR/config.json"
          chown ${cfg.primaryUser}: "$CONFIG_DIR/config.json"
          chmod 640 "$CONFIG_DIR/config.json"

          # The opencode sandbox policy is no longer copied here: it is merged
          # into ~/.config/opencode/opencode.json by the
          # contain-opencode-config-seed systemd unit.

          # OpenCode config, data & state directories
          for dir in \
            "${cfg.primaryHome}/.config/opencode" \
            "${cfg.primaryHome}/.local/share/opencode" \
            "${cfg.primaryHome}/.local/state/opencode"; do
            mkdir -p "$dir"
            chown ${cfg.primaryUser}: "$dir"
            chmod 770 "$dir"
          done

          # Fix ownership and permissions on existing data/state files.
          # This handles upgrades from older setups where files may have been
          # created with wrong UID/GID or restrictive permissions. auth.json
          # is included on purpose: OpenCode >= 1.17 writes /connect
          # credentials to it, so it must be agent- (group-) writable.
          for dir in \
            "${cfg.primaryHome}/.local/share/opencode" \
            "${cfg.primaryHome}/.local/state/opencode"; do
            ${pkgs.findutils}/bin/find "$dir" -not -group $(${pkgs.coreutils}/bin/id -gn ${cfg.primaryUser}) -exec ${pkgs.coreutils}/bin/chgrp $(${pkgs.coreutils}/bin/id -gn ${cfg.primaryUser}) {} + 2>/dev/null || true
            ${pkgs.findutils}/bin/find "$dir" -type f -not -perm -g+w -exec chmod g+w {} + 2>/dev/null || true
            ${pkgs.findutils}/bin/find "$dir" -type d -not -perm -g+wx -exec chmod g+wx {} + 2>/dev/null || true
          done
        '';
        deps = [ "users" ];
      };

      # Set up project directory permissions.
      # Only ensures directories are group-traversable (g+x) so the agent
      # can navigate via the mapped GID. File permissions are left as-is.
      contain-permissions = {
        text = ''
          ${lib.concatMapStringsSep "\n" (p: ''
            if [ -d "${p}" ]; then
              ${pkgs.findutils}/bin/find "${p}" -type d ! -perm -g+x -exec chmod g+x {} +
            fi
          '') cfg.projectPaths}
        '';
        deps = [ "contain-dirs" ];
      };
    };

    # -- Image build service --
    # Build / rebuild the container image after the full system is up.
    # This must NOT be a NixOS activation script: with systemd stage-1,
    # activation runs inside the initrd (chroot into /sysroot before
    # switch-root), where Podman has no network, no policy and no runtime.
    # A failing build there aborts activation before /etc/os-release exists,
    # so the boot dies with "Failed to start Switch Root". The same applies
    # to nixos-install's chroot. The image is a user-level application
    # concern; building it strictly after network-online is correct.
    systemd.services.contain-image = {
      description = "Build contAIn container image";
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      before = [ "contain.service" ];
      requiredBy = [ "contain.service" ];

      path = [
        pkgs.coreutils
        pkgs.podman
      ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        StateDirectory = "contain";
      };

      script = ''
        set -euo pipefail

        CONTAINER_DIR="${../container}"
        HASH_FILE="/var/lib/contain/containerfile.sha256"
        mkdir -p /var/lib/contain

        AGENT_UID=$(id -u ${cfg.agent.user} 2>/dev/null || echo ${toString cfg.agent.uid})
        # Use the primary user's GID and group name for the container.
        PRIMARY_GID=$(id -g ${cfg.primaryUser} 2>/dev/null)
        PRIMARY_GROUP=$(id -gn ${cfg.primaryUser} 2>/dev/null)

        # The image must be rebuilt when any of its build inputs change, not
        # only the Containerfile: the container/ context (a Nix store path
        # whose name changes with ANY file in it, incl. entrypoint.sh and
        # opencode-tui.sh), baked UID/GID, the OpenCode version pin and the
        # architecture all shape the result.
        CURRENT_HASH="$CONTAINER_DIR:$AGENT_UID:$PRIMARY_GID:${cfg.container.opencodeVersion}:${pkgs.stdenv.hostPlatform.linuxArch}"
        STORED_HASH=""
        if [ -f "$HASH_FILE" ]; then
          STORED_HASH=$(cat "$HASH_FILE")
        fi

        if [ "$CURRENT_HASH" != "$STORED_HASH" ] || \
           ! podman image exists localhost/contain:latest 2>/dev/null; then

          echo "contain: building container image..."
          podman build \
            --build-arg "AGENT_UID=$AGENT_UID" \
            --build-arg "AGENT_GID=$PRIMARY_GID" \
            --build-arg "AGENT_GROUP_NAME=$PRIMARY_GROUP" \
            --build-arg "OPENCODE_VERSION=${cfg.container.opencodeVersion}" \
            --build-arg "OPENCODE_ARCH=${pkgs.stdenv.hostPlatform.linuxArch}" \
            -t localhost/contain:latest \
            -f "$CONTAINER_DIR/Containerfile" \
            "$CONTAINER_DIR"

          echo "$CURRENT_HASH" > "$HASH_FILE"
          echo "contain: image built successfully."
        else
          echo "contain: container image up to date."
        fi
      '';
    };

    # -- OpenCode auth seed --
    # Merge a host-provided credential seed into the OpenCode auth store.
    # OpenCode >= 1.17 persists /connect credentials to auth.json itself, so
    # the file must stay agent-writable (0660) and runtime-added providers
    # must survive re-runs: the seed wins for its own keys, everything else
    # is preserved.
    systemd.services.contain-opencode-auth-seed = lib.mkIf (cfg.opencode.authSeedFile != null) {
      description = "Seed contAIn OpenCode auth.json";
      before = [ "contain.service" ];
      requiredBy = [ "contain.service" ];

      path = [
        pkgs.coreutils
        pkgs.jq
      ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        set -euo pipefail

        seed=${lib.escapeShellArg cfg.opencode.authSeedFile}
        dir="${cfg.primaryHome}/.local/share/opencode"
        dest="$dir/auth.json"

        if [ ! -r "$seed" ]; then
          echo "contain: OpenCode auth seed is not readable: $seed" >&2
          exit 1
        fi
        if ! jq -e . "$seed" > /dev/null 2>&1; then
          echo "contain: OpenCode auth seed is not valid strict JSON: $seed" >&2
          echo 'contain: expected a complete object, e.g. {"provider":{"type":"api","key":"..."}}' >&2
          exit 1
        fi

        primary_group="$(id -gn ${cfg.primaryUser})"
        install -d -o ${cfg.primaryUser} -g "$primary_group" -m 0770 "$dir"

        tmp="$(mktemp "$dir/.auth.json.XXXXXX")"
        if [ -s "$dest" ] && jq -e . "$dest" > /dev/null 2>&1; then
          # Existing store survives; the seed is authoritative for its keys.
          jq -s '.[0] * .[1]' "$dest" "$seed" > "$tmp"
        else
          # Normalize so the deployed store is always canonical JSON.
          jq . "$seed" > "$tmp"
        fi
        chown ${cfg.primaryUser}:"$primary_group" "$tmp"
        chmod 0660 "$tmp"
        mv -f "$tmp" "$dest"
      '';
    };

    # -- OpenCode config seed --
    # Deploy the OpenCode config as an agent-writable file: OpenCode persists
    # runtime changes (provider registration from /connect, helper files)
    # into its config, so a read-only config breaks those flows. Layering,
    # later wins: existing runtime config < host seed < sandbox policy. The
    # policy is last so the declarative sandbox posture is re-asserted on
    # every service start even if the agent edited the file at runtime.
    systemd.services.contain-opencode-config-seed = {
      description = "Seed contAIn OpenCode opencode.json";
      before = [ "contain.service" ];
      requiredBy = [ "contain.service" ];

      path = [
        pkgs.coreutils
        pkgs.jq
      ];

      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };

      script = ''
        set -euo pipefail

        policy=${opencodePolicy}
        dir="${cfg.primaryHome}/.config/opencode"
        dest="$dir/opencode.json"

        primary_group="$(id -gn ${cfg.primaryUser})"
        install -d -o ${cfg.primaryUser} -g "$primary_group" -m 0770 "$dir"

        inputs=()
        if [ -s "$dest" ] && jq -e . "$dest" > /dev/null 2>&1; then
          inputs+=("$dest")
        fi
        ${lib.optionalString (cfg.opencode.configSeedFile != null) ''
          seed=${lib.escapeShellArg cfg.opencode.configSeedFile}
          if [ ! -r "$seed" ] || ! jq -e . "$seed" > /dev/null 2>&1; then
            echo "contain: OpenCode config seed is not readable or not valid strict JSON: $seed" >&2
            exit 1
          fi
          inputs+=("$seed")
        ''}
        inputs+=("$policy")

        tmp="$(mktemp "$dir/.opencode.json.XXXXXX")"
        jq -s 'reduce .[] as $x ({}; . * $x)' "''${inputs[@]}" > "$tmp"
        chown ${cfg.primaryUser}:"$primary_group" "$tmp"
        chmod 0660 "$tmp"
        mv -f "$tmp" "$dest"
      '';
    };

    # -- On-demand socket activation --
    # contain-proxy.socket owns the public port. The first client connection
    # activates contain-proxy.service, whose Requires= pulls up the container
    # (and, transitively, image build + secret seeds). systemd-socket-proxyd
    # exits after idleTimeout with no connections; contain.service then has
    # no active dependent left and StopWhenUnneeded stops it. Long-lived
    # client connections (neovim SSE stream, attached TUI going through the
    # public port) keep the proxy — and therefore the container — alive.
    systemd.sockets.contain-proxy = lib.mkIf cfg.onDemand.enable {
      description = "contain on-demand activation socket";
      wantedBy = [ "sockets.target" ];
      listenStreams = [ "${cfg.server.host}:${toString cfg.server.port}" ];
    };

    systemd.services.contain-proxy = lib.mkIf cfg.onDemand.enable {
      description = "contain on-demand connection proxy";
      requires = [ "contain.service" ];
      after = [ "contain.service" ];

      serviceConfig = {
        ExecStart = lib.concatStringsSep " " [
          "${pkgs.systemd}/lib/systemd/systemd-socket-proxyd"
          "--exit-idle-time=${cfg.onDemand.idleTimeout}"
          "${cfg.server.host}:${toString cfg.server.internalPort}"
        ];
        PrivateTmp = true;
        ProtectSystem = "strict";
        ProtectHome = true;
      };
    };

    # -- Watcher service --
    # Follows the container lifecycle: contain.service wants it (WantedBy)
    # and PartOf stops it together with the container. It deliberately does
    # NOT want/require contain.service itself — that would count as an
    # active dependent and defeat StopWhenUnneeded in on-demand mode.
    systemd.services.contain-watcher = {
      description = "contain File Ownership Watcher";
      after       = [ "contain.service" ];
      partOf      = [ "contain.service" ];
      wantedBy    = [ "contain.service" ];

      path = [ pkgs.coreutils pkgs.inotify-tools ];

      serviceConfig = {
        Type       = "simple";
        ExecStart  = lib.concatStringsSep " " ([
          "${scripts}/lib/contain/contain-watcher.sh"
          cfg.primaryUser
          cfg.agent.user
        ] ++ cfg.projectPaths);
        Restart    = "on-failure";
        RestartSec = 5;
      };
    };

    # -- Commit service (oneshot, triggered by timer) --
    systemd.services.contain-commit = {
      description = "contain Container State Commit";

      path = [ pkgs.coreutils pkgs.podman pkgs.gawk pkgs.gnugrep ];

      serviceConfig = {
        Type      = "oneshot";
        ExecStart = "${scripts}/lib/contain/contain-commit.sh";
      };
    };

    # -- Commit timer --
    systemd.timers.contain-commit = {
      description = "Periodic contain Container Commit";
      wantedBy    = [ "timers.target" ];

      timerConfig = {
        OnCalendar = "daily";
        Persistent = true;
      };
    };
  };
}
